[package]
name = "i2c_hackery"
version = "0.1.0"
authors = ["Milo Mirate <mmirate@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.4"
linux-embedded-hal = { version = "0.3.0" }
may = "0.3.19"
regex-automata = "0.1.9"
thiserror = "1.0.24"
